name: dod
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  camera_camera: ^1.0.1
  rxdart: ^0.19.0
  dio: ^2.1.2
  cupertino_icons: ^0.1.2
  animated_text_kit: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

 
  assets:
  - assets/images/logo.png


 