name: dod
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  camera_camera: ^1.0.25
  rxdart: ^0.22.3
  dio: ">=2.1.2 <6.0.0"
  cupertino_icons: ^0.1.2
  animated_text_kit: ^1.3.0
  flutter_native_image:
    git: https://github.com/btastic/flutter_native_image.git

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

 
  assets:
  - assets/images/logo.png


 